name: deploy

on: [push, workflow_dispatch] # ✅ Remove space before comma

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Print version
        run: node -v

      - name: Install dependencies
        run: npm ci # ✅ Requires package-lock.json

      - name: Run tests
        run: npm test # ✅ Requires test script in package.json



              

            # - name: Deploy to server
            #   run: |
            #     echo "Deploying to server..."
            #     # Add your deployment commands here
            #     # For example, you might use rsync or scp to copy files to a remote server
