name: deploy
on: [push , workflow_dispatch] # Trigger on push and manual dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: Print version
              run: node -v

            - name: Install dependencies
              run: npm ci # Install dependencies using npm ci uses package lock file

            - name: Run tests
              run: npm test # Run tests using npm test


              

            # - name: Deploy to server
            #   run: |
            #     echo "Deploying to server..."
            #     # Add your deployment commands here
            #     # For example, you might use rsync or scp to copy files to a remote server
